name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: |
          curl -L https://api.nife.io/release/install.sh | sh
          export NIFECTL_INSTALL="/home/runner/.nife"
          export PATH="$NIFECTL_INSTALL/bin:$PATH"
          nifectl auth login --email dolly@nife.io  --password Dolly@Dhruv1234
          nifectl init
          
